### ISSUE TITLE
Mechanism to keep Go modules up to date

### ISSUE THREAD

**Issue by EvanBoyle** [pulumi/templates#114]
We need a mechanism to keep our `go.mod` files up to date as we release new versions of pulumi/pulumi and providers.

**Comment by EvanBoyle** [comment]
Just ran into an instance where a user hit a 5-month-old bug with a new project because `pulumi new go` references `v2.9.2` of the pulumi sdk.

**Comment by viveklak** [comment]
> Just ran into an instance where a user hit a 5-month-old bug with a new project because `pulumi new go` references `v2.9.2` of the pulumi sdk.

Similarly bunch of provider SDKs point to very old versions, e.g. `pulumi-aws` refers to a version from August. See https://github.com/pulumi/templates/pull/149 for PR to bump to latest for core pulumi and provider SDKs in the meantime.

**Comment by lblackstone** [comment]
@stack72 @jaxxstorm Do either of you have suggestions on how to implement this? My initial thought is one of the following:

1. Write a GHA in pulumi/pulumi to open PRs on downstream repos after a release
2. Use something like dependabot on all provider repos to detect new versions of dependencies

**Comment by stack72** [comment]
@lblackstone the trouble here is that PRs to update go.mod would have to use sed to update the value

Dependabot only works on a valid go project - ours are not valid projects as we don't have a go.sum and we don't have a valid go.mod due to templating

The same issue exists around go get this why sed is the only way. 

IMO this isn't really solvable with GHA - I think we may need to look at not specifying a version in go mod and go will try and get the latest

So if there is a path of

GitHub.com/Pulumi/Pulumi/v2

Then no version being specified in go.mod should bring in the latest v2 release (needs to be tested)
