### ISSUE TITLE
Always add the `main` entry in `package.json` on `pulumi new`

### ISSUE THREAD

**Issue by leezen** [pulumi/templates#291]
@leezen I think always adding the `main` entry in `package.json` on `pulumi new` will help avoiding such issues from the beginning. Took me some time to figure this out the first time I've seen this.

_Originally posted by @Dominik-K in https://github.com/pulumi/pulumi-aws/issues/933#issuecomment-610859758_

**Comment by semiautomatix** [comment]
I'm going to re-open this, as I'm having an issue.

Basically I use the `main` entry point to submit my project for `publishing` in my online repository. 

I only `pulumi up` locally and that is in a separate folder for testing or deploying for local. 

```
Diagnostics:
  pulumi:pulumi:Stack (ret-aws-serverless-dev):
    error: Error: Error reading file '/workspace/ret-aws-serverless/bin/package.json' when computing package dependencies. Error: ENOENT: no such file or directory, open '/workspace/ret-aws-serverless/bin/package.json'
        at readFile (/workspace/ret-aws-serverless/node_modules/.pnpm/@pulumi+pulumi@3.55.0/node_modules/@pulumi/runtime/closure/codePaths.ts:250:19)
        at computeDependenciesDirectlyFromPackageFile (/workspace/ret-aws-serverless/node_modules/.pnpm/@pulumi+pulumi@3.55.0/node_modules/@pulumi/runtime/closure/codePaths.ts:229:22)
        at /workspace/ret-aws-serverless/node_modules/.pnpm/@pulumi+pulumi@3.55.0/node_modules/@pulumi/runtime/closure/codePaths.ts:187:36
        at /workspace/ret-aws-serverless/node_modules/.pnpm/read-package-tree@5.3.1/node_modules/read-package-tree/rpt.js:162:20
```

**Comment by AaronFriel** [comment]
Hey @semiautomatix, thanks for flagging your issue. Would you mind copy your comment into a new issue in the Pulumi CLI & Node SDK repository at github.com/pulumi/pulumi?

This issue is primarily about adjusting the templates we have.

Regarding your issue, though, I think you should remove `bin/` from your `Pulumi.yaml` file. The `main` property of a project file is the root directory of the project, hence the error referencing `bin/package.json`:

> error: Error: Error reading file '/workspace/ret-aws-serverless/bin/package.json'
