### ISSUE TITLE
Generated requirements.txt file has redundant line

### ISSUE THREAD

**Issue by rbanffy** [pulumi/templates#341]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When creating a new Python project, the `requirements.txt` file specifies both `pulumi` and `pulumi-aws` as requirements. Since `pulumi-aws` already requires `pulumi`, the first is redundant.

### Affected area/feature

New Python-based project creation

**Comment by cnunciato** [comment]
Paging @kpitzen, who probably knows the answer to this one. I ask as a non-Python expert, and because we seem include an explicit `pulumi` entry in all of our `requirements.txt`s. Should we remove these across the board? Any potential issues, or would such a change work for all Python users? Or would it be better to keep it?

**Comment by kpitzen** [comment]
I hesitate to call them redundant, as it's often useful to explicitly define dependencies actually used in a project rather than assume that transitiveness is a promise forever.  As far as I'm concerned, I'd leave them (and would likely include both separately in any project I write myself).

**Comment by cnunciato** [comment]
Thanks @kpitzen, that makes sense. I think we'll close this issue, then -- thank you @rbanffy! Always good to keep an eye on these kinds of things.
