### ISSUE TITLE
Missing GCP Templates for Multiple Examples & Languages.

### ISSUE THREAD

**Issue by timbohiatt** [pulumi/templates#402]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently AWS Template patterns have been constructed for 3 template areas on the Pulumi Site. These include Serverless, Kubernetes & Container Services. There is currently a gap (where I can already see work is happening) where GCP templates have not been created for these templates. I would like to track this gap by formally raising it as an issue. 

In addition I am committing from Google's side too assisting in filling some of these gaps where I @timbohiatt am able to via way of subsequent pull requests. 

In this particular Issue I will focus on the code examples that are required here in Pulumi/templates Repo and therefore can be used for Pulumi New / Pulumi Up. Subsequent Issue & PR's will need to be raised after code acceptance to the Pulumi/Hugo repo to include documentation on the official Pulumi website.

### Affected area/feature

[Missing GCP Pulumi/Template](https://www.pulumi.com/templates/): 
- [Container Service Templates](https://www.pulumi.com/templates/container-service/)
- [Serverless Templates](https://www.pulumi.com/templates/serverless-application/)
- [Kubernetes Templates](https://www.pulumi.com/templates/kubernetes/)

**Comment by scottslowe** [comment]
@timbohiatt Hi Tim! Thanks for opening this issue. @cnunciato and I are currently working on a couple of GCP-focused templates, including:

* Kubernetes on GCP (via GKE)
* Containers on GCP

There should already be a templates for a static website on GCP and serverless on GCP.

If you are interested in writing templates, I'd like to coordinate with you so that we aren't inadvertently duplicating effort. There are a couple more templates we'd like to have, and we'd also certainly love you to review the existing templates.

For example, if you have time to review the Kubernetes on GCP templates that would be very helpful: https://github.com/pulumi/templates/pull/394

**Comment by scottslowe** [comment]
@timbohiatt I just dropped you a DM on Slack so that you have my information. Happy to catch up and discuss how @cnunciato and I are creating the templates, and talk about where you and others within GCP could help.

**Comment by cnunciato** [comment]
@scottslowe @timbohiatt Closing this as complete, but feel free to reopen if there's anything we've missed. Thanks!
