### ISSUE TITLE
Use project name in package.json for Node.js templates

### ISSUE THREAD

**Issue by jen20** [pulumi/templates#76]
When using `pulumi new aws-typescript` (for example), the user is prompted for a project name which is used in `Pulumi.yaml`. However, the same name is not used in the `name` field of the `package.json` file - something I believe we should reconsider.

**Comment by pgavlin** [comment]
This seems reasonable to me. @justinvp @lukehoban @CyrusNajmabadi ?

**Comment by justinvp** [comment]
We used to do this, but stopped doing it in https://github.com/pulumi/templates/pull/40. Since then we've gotten more strict on validating project names and now always show the `npm install` output, so I don't see any downside to adding it back. Will just need to double check what characters npm considers to be invalid.

**Comment by CyrusNajmabadi** [comment]
it's fine with me :)
